#!/usr/bin/env sh
set -o errexit
set -o nounset

# install ohmyzsh and plugins
sudo dnf install zsh -y
rm -rf $HOME/.oh-my-zsh && sh -c "RUNZSH=no $(wget -qO- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# add symlinks
rm -f $HOME/.zshrc
rm -f $HOME/.p10k.zsh

ln -s $(pwd)/dotfiles/.zshrc $HOME/.zshrc
ln -s $(pwd)/dotfiles/.p10k.zsh $HOME/.p10k.zsh
