#!/usr/bin/env sh
set -o errexit
set -o nounset

# add symlinks
rm -f $HOME/.zshrc
rm -f $HOME/.p10k.zsh
ln -s /.zshrc $HOME/.zshrc
ln -s /.p10k.zsh $HOME/.p10k.zsh

# install ohmyzsh and plugins
sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# load custom terminal profile
cd profiles
dconf load /org/gnome/terminal/legacy/profiles:/ < gnome-terminal-profiles.dconf
