#!/usr/bin/env sh
set -o errexit
set -o nounset

# Keep-alive: update existing user's password timestamp until this script finishes on the current machine.
while true; do sudo --non-interactive true; sleep 60; kill -s 0 "$$" || exit; done 2> /dev/null &

# Theme, Icons and Cursor
mkdir -p $HOME/.icons
mkdir -p $HOME/.themes
mkdir -p $HOME/.fonts

# fonts and reload cache
cp -r fonts/ $HOME/.fonts
fc-cache -f

rm -rf $HOME/.themes/gtk-master && unzip -q themes/dracula-gtk.zip -d $HOME/.themes/
rm -rf $HOME/.icons/Simp1e-dark && tar -xf themes/Simp1e-dark.tgz -C $HOME/.icons/
rm -rf $HOME/.icons/Dracula && unzip -q themes/dracula-icons.zip -d $HOME/.icons/

# set wallpaper
gsettings set org.gnome.desktop.background picture-uri-dark ''$(pwd)'/images/wallpaper.jpg'

# configure interface
gsettings set org.gnome.desktop.interface gtk-theme "gtk-master"
gsettings set org.gnome.desktop.wm.preferences theme "gtk-master"
gsettings set org.gnome.desktop.interface icon-theme 'Dracula'
gsettings set org.gnome.desktop.interface cursor-theme 'Simp1e-dark'
gsettings set org.gnome.mutter center-new-windows 'true'
gsettings set org.gnome.desktop.interface enable-animations false

# set typeface settings
gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
gsettings set org.gnome.desktop.interface font-hinting 'none'
gsettings set org.gnome.desktop.interface document-font-name 'Rec Mono Semicasual 10'
gsettings set org.gnome.desktop.interface font-name 'Rec Mono Semicasual 10'
gsettings set org.gnome.desktop.interface monospace-font-name 'Rec Mono Linear 10'
gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Rec Mono Semicasual Bold 10'

# load custom terminal profile
dconf load /org/gnome/terminal/legacy/profiles:/ < $(pwd)/themes/gnome-terminal-profiles.dconf

# update sublime profile
cp -u $(pwd)/themes/Preferences.sublime-settings $HOME/.config/sublime-text/Packages/User/Preferences.sublime-settings
