#!/usr/bin/env sh
set -o errexit
set -o nounset

# Keep-alive: update existing user's password timestamp until this script finishes on the current machine.
while true; do sudo --non-interactive true; sleep 60; kill -s 0 "$$" || exit; done 2> /dev/null &

sudo dnf config-manager --set-disabled google-chrome
sudo dnf config-manager --set-disabled phracek-PyCharm
sudo dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'


sudo dnf check-update
sudo dnf install --assumeyes \
sublime-text \
zsh \
neofetch \
code \
gnome-tweak-tool

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install --assumeyes flathub \
com.discordapp.Discord \
com.skype.Client \
com.spotify.Client \
md.obsidian.Obsidian \
org.videolan.VLC \
org.gnome.Extensions
