#!/usr/bin/env sh
set -o errexit
set -o nounset

# Keep-alive: update existing user's password timestamp until this script finishes on the current machine.
while true; do sudo --non-interactive true; sleep 60; kill -s 0 "$$" || exit; done 2> /dev/null &

cp -r .fonts/ ${HOME}/.fonts
cp -r .icons/ ${HOME}/.icons

# Theme, Icons and Cursor
git clone --depth=1 https://github.com/dracula/gtk.git ~/.themes/Dracula
wget -qO- https://git.io/papirus-icon-theme-install | DESTDIR="$HOME/.icons" sh

gsettings set org.gnome.desktop.interface gtk-theme "Dracula"
gsettings set org.gnome.desktop.wm.preferences theme "Dracula"
gsettings set org.gnome.desktop.interface icon-theme 'ePapirus-Dark'
gsettings set org.gnome.desktop.interface cursor-theme 'Simp1e-dark'

gsettings set org.gnome.mutter center-new-windows 'true'
gsettings set org.gnome.desktop.interface enable-animations false

gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
gsettings set org.gnome.desktop.interface font-hinting 'none'
gsettings set org.gnome.desktop.interface document-font-name 'Rational Display Test 11'
gsettings set org.gnome.desktop.interface font-name 'Rational Display Test 11'
gsettings set org.gnome.desktop.interface monospace-font-name 'Fira Code 11'
gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Rational Display Test Semi-Bold 11'

dconf load /org/gnome/terminal/legacy/profiles:/ < profiles/gnome-terminal-profiles.dconf
