#!/usr/bin/env sh
set -o errexit
set -o nounset

# Ask for the administrator's password in advance.
sudo --validate

# Keep-alive: update existing user's password timestamp until this script finishes on the current machine.
while true; do sudo --non-interactive true; sleep 60; kill -s 0 "$$" || exit; done 2> /dev/null &

# Part I: System Updates
dnf config-manager --set-disabled google-chrome
dnf config-manager --set-disabled phracek-PyCharm
# sudo dnf install --assumeyes akmod-nvidia xorg-x11-drv-nvidia xorg-x11-drv-nvidia-cuda
sudo dnf update --refresh --assumeyes && reboot
